language: java

jdk:
  - openjdk8
services:
- docker

before_install:
- cd lab5
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script:
- mvn package
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_NAME" --password-stdin
- docker build -t ying98/ds_group7 .
- docker push ying98/ds_group7:latest
- docker run -d -p 8081:8081 ying98/ds_group7
- docker ps -a
