language: java

jdk:
- openjdk8

services:
- docker
# - mysql

sudo: required

before_install:
- cd lab5
# - mysql -e 'create database lab5;'
# - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; FLUSH PRIVILEGES;"
# - sudo service mysql restart
# - sudo mysql -e "use lab5;CREATE TABLE commodity(id INT NOT NULL PRIMARY KEY, name VARCHAR(11) NULL,price DOUBLE NULL,currency  VARCHAR(5)  NULL,inventory INT NULL) ENGINE = InnoDB;"
# - sudo mysql -e "use lab5;CREATE TABLE result(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,initiator VARCHAR(5) NULL,success VARCHAR(5) NULL,paid DOUBLE NULL) ENGINE = InnoDB;"
# - sudo mysql -e "use lab5;show tables;"

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true

# addons:
#   apt:
#     sources:
#       - mysql-5.7-trusty
#     packages:
#       - mysql-server
#       - mysql-client

script:
- mvn package -DskipTests=true
# - java -jar  ./target/app-0.0.1-SNAPSHOT.jar
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_NAME" --password-stdin
# - docker pull mysql:5.7
# - docker run -p 3306:3306 --name dsgroup7 -v $PWD/conf:/etc/mysql/conf.d -v $PWD/logs:/logs -v $PWD/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD= -d mysql:5.7
- docker build -t ying98/ds_group7 .
- docker push ying98/ds_group7:latest
- docker run -d -p 8081:8081 ying98/ds_group7
- docker ps -a
